version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=${POSTGRES_SONARQUBE_PASSWORD}  #env variable
    volumes:
      - sonarqube_data:/opt/sonarqube/
    networks:
      - sonarqube_network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarqube_network

volumes:
  postgres_data:
    driver: local
  sonarqube_data:
    driver: local

networks:
  sonarqube_network: